when:
  - branch: main
    event:
      - push
      - manual
      - cron

steps:
- name: Publish Container Image
  image: woodpeckerci/plugin-docker-buildx
  settings:
    platforms: linux/amd64,linux/arm/v6,linux/arm64/v8
    # Replace this with your own Git host
    repo: git.mattcen.com/${CI_REPO}
    # Replace this with your own Git host
    registry: git.mattcen.com
    tags: latest
    username: ${CI_REPO_OWNER}
    password:
      from_secret: DOCKER_PASSWORD
    context: django/
    dockerfile: django/Dockerfile
    # Replace this with your own Git host
    cache_from: type=registry,ref=git.mattcen.com/${CI_REPO}:main
    cache_to: type=registry,ref=git.mattcen.com/${CI_REPO}:main
