services:
  # To use an built-in Postgres server, uncomment this service
  #db:
  #  # Use regular Postgres by default
  #  image: postgres:15.3-bullseye
  #  # Use PostGIS for spatial apps
  #  #image: postgis/postgis:15-3.3
  #  env_file: .env
  #  volumes:
  #    - db_data:/var/lib/postgresql/data
  #  healthcheck:
  #    test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
  #    interval: 10s
  #    timeout: 5s
  #    retries: 5
  #  restart: "unless-stopped"

  app:
    image: localhost/your_app_image_here
    build:
      context: ./django
      # To build image with extra dev tools
      #dockerfile: Dockerfile.dev
    command: python -m gunicorn myproject.wsgi -b 0.0.0.0:8000
    env_file: .env
    volumes:
      - media_files:/media
      # Comment this out if you're not using SQLite
      - ./db:/db
    restart: "unless-stopped"
    # To use an built-in Postgres server, uncomment this dependency
    #depends_on:
    #  db:
    #    condition: service_healthy

  web:
    image: ghcr.io/nginx/nginx-unprivileged:alpine
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "$APP_PORT:80"
    depends_on:
      - app
    volumes:
      - media_files:/media
    healthcheck:
      test: '[ "$(curl -L -o /dev/null -s -w "%{http_code}\n" http://localhost/.nginx_healthcheck)" = 200 ]'
      interval: 10s
      timeout: 5s
      retries: 5

configs:
  nginx_conf:
    #file: ./nginx.conf
    content: |
      upstream webapp { server ${WEB_APP_HOST}; }
      server {
          listen 80;
          location / {
              proxy_pass http://webapp;
              proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
              proxy_set_header Host $$host;
              proxy_redirect off;
          }
          location /media/ { alias /media/; }
          location /.nginx_healthcheck {
            return 200 'running';
            default_type application/text;
          }
      }

volumes:
  db_data:
  media_files:
